working_directory = ""
detectors = ["GE1", "GE3"]
run_number = 0

[display]
screen_resolution = 2

[databases]
gamma_database = "IAEA"
muonic_xray_database = "legacy" # Not sure where the muonic xray database is from
electronic_xray_database = "xray_booklet_2009"

[plot]
fill_colour = "yellow"

[normalisation]
normalise_counts = true
normalise_spill = false

[detectors.GE1]
e_corr_offset = 0
e_corr_gradient = 1
use_energy_correction = false
effCorrParams = [93.2, 59.2, -13.6, 1.35, -0.049]

[detectors.GE2]
e_corr_offset = 0
e_corr_gradient = 1
use_energy_correction = false

[detectors.GE3]
e_corr_offset = 0
e_corr_gradient = 1
use_energy_correction = false
EffCorrParams = [-1.79, 0.805, -0.0711, 0, 0]

[detectors.GE4]
e_corr_offset = 0
e_corr_gradient = 1
use_energy_correction = false
