[general]
working_directory = "C:/Users/matea/PycharmProjects/EVA/test_data"
default_run_num = 3065
all_detectors = ["GE1", "GE2", "GE3", "GE4"]

[display]
screen_resolution = 2

[database]
gamma_db = "IAEA"
mu_xray_db = "mudirac"
e_xray_db = "xray_booklet_2009"
gamma_intensity_threshold = 20

[plot]
fill_colour = "pink"

[SRIM]
installation_directory = "C:/Users/matea/SRIM2013"
output_directory = "C:/Users/matea/SRIM2013/SRIM Outputs/"

