# Form implementation generated from reading ui file 'detector_grouping_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Energycorrections(object):
    def setupUi(self, Energycorrections):
        Energycorrections.setObjectName("Energycorrections")
        Energycorrections.resize(383, 464)
        self.gridLayout = QtWidgets.QGridLayout(Energycorrections)
        self.gridLayout.setObjectName("gridLayout")
        self.RunListTable = BaseTable(parent=Energycorrections)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunListTable.sizePolicy().hasHeightForWidth())
        self.RunListTable.setSizePolicy(sizePolicy)
        self.RunListTable.setMinimumSize(QtCore.QSize(300, 0))
        self.RunListTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.RunListTable.setRowCount(50)
        self.RunListTable.setColumnCount(2)
        self.RunListTable.setObjectName("RunListTable")
        item = QtWidgets.QTableWidgetItem()
        self.RunListTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RunListTable.setHorizontalHeaderItem(1, item)
        self.RunListTable.horizontalHeader().setDefaultSectionSize(100)
        self.gridLayout.addWidget(self.RunListTable, 1, 0, 1, 2)
        self.current_profile_label = QtWidgets.QLabel(parent=Energycorrections)
        self.current_profile_label.setObjectName("current_profile_label")
        self.gridLayout.addWidget(self.current_profile_label, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=Energycorrections)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.save_profile_button = QtWidgets.QPushButton(parent=self.widget)
        self.save_profile_button.setObjectName("save_profile_button")
        self.gridLayout_2.addWidget(self.save_profile_button, 0, 0, 1, 1)
        self.load_profile_button = QtWidgets.QPushButton(parent=self.widget)
        self.load_profile_button.setObjectName("load_profile_button")
        self.gridLayout_2.addWidget(self.load_profile_button, 0, 1, 1, 1)
        self.apply_profile_button = QtWidgets.QPushButton(parent=self.widget)
        self.apply_profile_button.setObjectName("apply_profile_button")
        self.gridLayout_2.addWidget(self.apply_profile_button, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.widget, 2, 0, 1, 2)

        self.retranslateUi(Energycorrections)
        QtCore.QMetaObject.connectSlotsByName(Energycorrections)

    def retranslateUi(self, Energycorrections):
        _translate = QtCore.QCoreApplication.translate
        Energycorrections.setWindowTitle(_translate("Energycorrections", "Dialog"))
        item = self.RunListTable.horizontalHeaderItem(0)
        item.setText(_translate("Energycorrections", "Group"))
        item = self.RunListTable.horizontalHeaderItem(1)
        item.setText(_translate("Energycorrections", "Detectors"))
        self.current_profile_label.setText(_translate("Energycorrections", "Current Profile:"))
        self.save_profile_button.setText(_translate("Energycorrections", "Save Profile"))
        self.load_profile_button.setText(_translate("Energycorrections", "Load Profile"))
        self.apply_profile_button.setText(_translate("Energycorrections", "Apply"))
from EVA.gui.base.base_table import BaseTable


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Energycorrections = QtWidgets.QDialog()
    ui = Ui_Energycorrections()
    ui.setupUi(Energycorrections)
    Energycorrections.show()
    sys.exit(app.exec())
