# Form implementation generated from reading ui file 'detector_grouping_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_DetectorGrouping(object):
    def setupUi(self, DetectorGrouping):
        DetectorGrouping.setObjectName("DetectorGrouping")
        DetectorGrouping.resize(400, 310)
        self.gridLayout = QtWidgets.QGridLayout(DetectorGrouping)
        self.gridLayout.setObjectName("gridLayout")
        self.ConfigTable = BaseTable(parent=DetectorGrouping)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConfigTable.sizePolicy().hasHeightForWidth())
        self.ConfigTable.setSizePolicy(sizePolicy)
        self.ConfigTable.setMinimumSize(QtCore.QSize(0, 0))
        self.ConfigTable.setAutoFillBackground(False)
        self.ConfigTable.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ConfigTable.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff
        )
        self.ConfigTable.setRowCount(2)
        self.ConfigTable.setColumnCount(2)
        self.ConfigTable.setObjectName("ConfigTable")
        item = QtWidgets.QTableWidgetItem()
        self.ConfigTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ConfigTable.setHorizontalHeaderItem(1, item)
        self.ConfigTable.horizontalHeader().setDefaultSectionSize(100)
        self.gridLayout.addWidget(self.ConfigTable, 1, 0, 1, 2)
        self.widget = QtWidgets.QWidget(parent=DetectorGrouping)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.new_profile_name_line_edit = QtWidgets.QLineEdit(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.new_profile_name_line_edit.sizePolicy().hasHeightForWidth()
        )
        self.new_profile_name_line_edit.setSizePolicy(sizePolicy)
        self.new_profile_name_line_edit.setObjectName("new_profile_name_line_edit")
        self.gridLayout_2.addWidget(self.new_profile_name_line_edit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.save_profile_button = QtWidgets.QPushButton(parent=self.widget)
        self.save_profile_button.setObjectName("save_profile_button")
        self.gridLayout_2.addWidget(self.save_profile_button, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.widget, 2, 0, 1, 2)
        self.current_profile_label = QtWidgets.QLabel(parent=DetectorGrouping)
        self.current_profile_label.setObjectName("current_profile_label")
        self.gridLayout.addWidget(self.current_profile_label, 0, 0, 1, 1)
        self.saved_profile_options_combobox = QtWidgets.QComboBox(
            parent=DetectorGrouping
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.saved_profile_options_combobox.sizePolicy().hasHeightForWidth()
        )
        self.saved_profile_options_combobox.setSizePolicy(sizePolicy)
        self.saved_profile_options_combobox.setObjectName(
            "saved_profile_options_combobox"
        )
        self.gridLayout.addWidget(self.saved_profile_options_combobox, 0, 1, 1, 1)

        self.retranslateUi(DetectorGrouping)
        QtCore.QMetaObject.connectSlotsByName(DetectorGrouping)

    def retranslateUi(self, DetectorGrouping):
        _translate = QtCore.QCoreApplication.translate
        DetectorGrouping.setWindowTitle(_translate("DetectorGrouping", "Dialog"))
        item = self.ConfigTable.horizontalHeaderItem(0)
        item.setText(_translate("DetectorGrouping", "Group"))
        item = self.ConfigTable.horizontalHeaderItem(1)
        item.setText(_translate("DetectorGrouping", "Detectors"))
        self.label.setText(_translate("DetectorGrouping", "Save As:"))
        self.save_profile_button.setText(
            _translate("DetectorGrouping", "Save New Profile")
        )
        self.current_profile_label.setText(
            _translate("DetectorGrouping", "Current Profile:")
        )


from EVA.gui.base.base_table import BaseTable


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    DetectorGrouping = QtWidgets.QDialog()
    ui = Ui_DetectorGrouping()
    ui.setupUi(DetectorGrouping)
    DetectorGrouping.show()
    sys.exit(app.exec())
