# Form implementation generated from reading ui file 'efficiency_corrections.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EfficiencyCorrections(object):
    def setupUi(self, EfficiencyCorrections):
        EfficiencyCorrections.setObjectName("EfficiencyCorrections")
        EfficiencyCorrections.resize(512, 341)
        self.formLayout = QtWidgets.QFormLayout(EfficiencyCorrections)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(parent=EfficiencyCorrections)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.efficiency_correction_units_combobox = QtWidgets.QComboBox(parent=EfficiencyCorrections)
        self.efficiency_correction_units_combobox.setObjectName("efficiency_correction_units_combobox")
        self.efficiency_correction_units_combobox.addItem("")
        self.efficiency_correction_units_combobox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.efficiency_correction_units_combobox)
        self.correction_table = BaseTable(parent=EfficiencyCorrections)
        self.correction_table.setObjectName("correction_table")
        self.correction_table.setColumnCount(8)
        self.correction_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.correction_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.correction_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.correction_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.correction_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.correction_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.correction_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.correction_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.correction_table.setHorizontalHeaderItem(7, item)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.correction_table)
        self.label_3 = QtWidgets.QLabel(parent=EfficiencyCorrections)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.cutoff_energy_line_edit = QtWidgets.QLineEdit(parent=EfficiencyCorrections)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cutoff_energy_line_edit.sizePolicy().hasHeightForWidth())
        self.cutoff_energy_line_edit.setSizePolicy(sizePolicy)
        self.cutoff_energy_line_edit.setObjectName("cutoff_energy_line_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cutoff_energy_line_edit)
        self.low_energy_label = QtWidgets.QLabel(parent=EfficiencyCorrections)
        self.low_energy_label.setObjectName("low_energy_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.low_energy_label)
        self.high_energy_label = QtWidgets.QLabel(parent=EfficiencyCorrections)
        self.high_energy_label.setObjectName("high_energy_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.high_energy_label)
        self.label = QtWidgets.QLabel(parent=EfficiencyCorrections)
        self.label.setObjectName("label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)

        self.retranslateUi(EfficiencyCorrections)
        QtCore.QMetaObject.connectSlotsByName(EfficiencyCorrections)

    def retranslateUi(self, EfficiencyCorrections):
        _translate = QtCore.QCoreApplication.translate
        EfficiencyCorrections.setWindowTitle(_translate("EfficiencyCorrections", "Dialog"))
        self.label_2.setText(_translate("EfficiencyCorrections", "Efficiency correction units:"))
        self.efficiency_correction_units_combobox.setItemText(0, _translate("EfficiencyCorrections", "Percentage"))
        self.efficiency_correction_units_combobox.setItemText(1, _translate("EfficiencyCorrections", "Fraction"))
        item = self.correction_table.horizontalHeaderItem(0)
        item.setText(_translate("EfficiencyCorrections", "Detector"))
        item = self.correction_table.horizontalHeaderItem(1)
        item.setText(_translate("EfficiencyCorrections", "A"))
        item = self.correction_table.horizontalHeaderItem(2)
        item.setText(_translate("EfficiencyCorrections", "B"))
        item = self.correction_table.horizontalHeaderItem(3)
        item.setText(_translate("EfficiencyCorrections", "C"))
        item = self.correction_table.horizontalHeaderItem(4)
        item.setText(_translate("EfficiencyCorrections", "D"))
        item = self.correction_table.horizontalHeaderItem(5)
        item.setText(_translate("EfficiencyCorrections", "E"))
        item = self.correction_table.horizontalHeaderItem(6)
        item.setText(_translate("EfficiencyCorrections", "F"))
        item = self.correction_table.horizontalHeaderItem(7)
        item.setText(_translate("EfficiencyCorrections", "Use"))
        self.label_3.setText(_translate("EfficiencyCorrections", "Low-High Energy Cutoff"))
        self.low_energy_label.setText(_translate("EfficiencyCorrections", "Low energy correction function: exp((a + b*(log(x/100) + c*(log(x/100)**2))"))
        self.high_energy_label.setText(_translate("EfficiencyCorrections", "High energy correction function: exp((d + e*(log(x/1000) + f*(log(x/1000)**2))"))
        self.label.setText(_translate("EfficiencyCorrections", "Y = Y / efficiency(x)"))
from EVA.gui.base.base_table import BaseTable


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EfficiencyCorrections = QtWidgets.QDialog()
    ui = Ui_EfficiencyCorrections()
    ui.setupUi(EfficiencyCorrections)
    EfficiencyCorrections.show()
    sys.exit(app.exec())
