# Form implementation generated from reading ui file 'C:\Users\matea\PycharmProjects\EVA\src\EVA\gui\ui_files\energy_correction_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Energycorrections(object):
    def setupUi(self, Energycorrections):
        Energycorrections.setObjectName("Energycorrections")
        Energycorrections.resize(439, 284)
        self.gridLayout = QtWidgets.QGridLayout(Energycorrections)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=Energycorrections)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 2)
        self.correction_table = BaseTable(parent=Energycorrections)
        self.correction_table.setObjectName("correction_table")
        self.correction_table.setColumnCount(4)
        self.correction_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.correction_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.correction_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.correction_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.correction_table.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.correction_table, 1, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Energycorrections)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Apply
            | QtWidgets.QDialogButtonBox.StandardButton.Cancel
        )
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(parent=Energycorrections)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)

        self.retranslateUi(Energycorrections)
        self.buttonBox.accepted.connect(Energycorrections.accept)  # type: ignore
        self.buttonBox.rejected.connect(Energycorrections.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Energycorrections)

    def retranslateUi(self, Energycorrections):
        _translate = QtCore.QCoreApplication.translate
        Energycorrections.setWindowTitle(_translate("Energycorrections", "Dialog"))
        self.label.setText(
            _translate("Energycorrections", "Correction function: y = Ax + B")
        )
        item = self.correction_table.horizontalHeaderItem(0)
        item.setText(_translate("Energycorrections", "Detector"))
        item = self.correction_table.horizontalHeaderItem(1)
        item.setText(_translate("Energycorrections", "A"))
        item = self.correction_table.horizontalHeaderItem(2)
        item.setText(_translate("Energycorrections", "B"))
        item = self.correction_table.horizontalHeaderItem(3)
        item.setText(_translate("Energycorrections", "Use correction"))
        self.label_2.setText(_translate("Energycorrections", "Set energy corrections"))


from EVA.gui.base.base_table import BaseTable


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Energycorrections = QtWidgets.QDialog()
    ui = Ui_Energycorrections()
    ui.setupUi(Energycorrections)
    Energycorrections.show()
    sys.exit(app.exec())
