# Form implementation generated from reading ui file 'fit_table_plot.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_fit_table_plot(object):
    def setupUi(self, fit_table_plot):
        fit_table_plot.setObjectName("fit_table_plot")
        fit_table_plot.resize(914, 808)
        self.horizontalLayout = QtWidgets.QHBoxLayout(fit_table_plot)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plot_container_widget = QtWidgets.QStackedWidget(parent=fit_table_plot)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(
            self.plot_container_widget.sizePolicy().hasHeightForWidth()
        )
        self.plot_container_widget.setSizePolicy(sizePolicy)
        self.plot_container_widget.setStyleSheet("background: white")
        self.plot_container_widget.setObjectName("plot_container_widget")
        self.plot = PlotWidget()
        self.plot.setObjectName("plot")
        self.plot_container_widget.addWidget(self.plot)
        self.model_plot = PlotWidget()
        self.model_plot.setObjectName("model_plot")
        self.plot_container_widget.addWidget(self.model_plot)
        self.horizontalLayout.addWidget(self.plot_container_widget)
        self.side_panel_tabs = QtWidgets.QWidget(parent=fit_table_plot)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.side_panel_tabs.sizePolicy().hasHeightForWidth()
        )
        self.side_panel_tabs.setSizePolicy(sizePolicy)
        self.side_panel_tabs.setMaximumSize(QtCore.QSize(700, 16777215))
        self.side_panel_tabs.setObjectName("side_panel_tabs")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.side_panel_tabs)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.peak_params_label = QtWidgets.QLabel(parent=self.side_panel_tabs)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.peak_params_label.setFont(font)
        self.peak_params_label.setObjectName("peak_params_label")
        self.gridLayout_2.addWidget(self.peak_params_label, 3, 0, 1, 1)
        self.fit_settings_widget = QtWidgets.QWidget(parent=self.side_panel_tabs)
        self.fit_settings_widget.setObjectName("fit_settings_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.fit_settings_widget)
        self.gridLayout_3.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mom_range_min_line_edit = QtWidgets.QLineEdit(
            parent=self.fit_settings_widget
        )
        self.mom_range_min_line_edit.setObjectName("mom_range_min_line_edit")
        self.gridLayout_3.addWidget(self.mom_range_min_line_edit, 0, 1, 1, 1)
        self.loaded_fit_table_label_2 = QtWidgets.QLabel(
            parent=self.fit_settings_widget
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.loaded_fit_table_label_2.sizePolicy().hasHeightForWidth()
        )
        self.loaded_fit_table_label_2.setSizePolicy(sizePolicy)
        self.loaded_fit_table_label_2.setObjectName("loaded_fit_table_label_2")
        self.gridLayout_3.addWidget(self.loaded_fit_table_label_2, 2, 0, 1, 2)
        self.auto_e_range_label = QtWidgets.QLabel(parent=self.fit_settings_widget)
        self.auto_e_range_label.setObjectName("auto_e_range_label")
        self.gridLayout_3.addWidget(self.auto_e_range_label, 0, 0, 1, 1)
        self.plot_parameter_comboBox = QtWidgets.QComboBox(
            parent=self.fit_settings_widget
        )
        self.plot_parameter_comboBox.setObjectName("plot_parameter_comboBox")
        self.plot_parameter_comboBox.addItem("")
        self.plot_parameter_comboBox.addItem("")
        self.plot_parameter_comboBox.addItem("")
        self.gridLayout_3.addWidget(self.plot_parameter_comboBox, 2, 2, 1, 1)
        self.mom_range_max_line_edit = QtWidgets.QLineEdit(
            parent=self.fit_settings_widget
        )
        self.mom_range_max_line_edit.setObjectName("mom_range_max_line_edit")
        self.gridLayout_3.addWidget(self.mom_range_max_line_edit, 0, 2, 1, 1)
        self.fit_settings_widget_2 = QtWidgets.QWidget(parent=self.fit_settings_widget)
        self.fit_settings_widget_2.setObjectName("fit_settings_widget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.fit_settings_widget_2)
        self.gridLayout_4.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.auto_e_range_label_2 = QtWidgets.QLabel(parent=self.fit_settings_widget_2)
        self.auto_e_range_label_2.setObjectName("auto_e_range_label_2")
        self.gridLayout_4.addWidget(self.auto_e_range_label_2, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.fit_settings_widget_2, 1, 0, 1, 1)
        self.e_range_max_line_edit = QtWidgets.QLineEdit(
            parent=self.fit_settings_widget
        )
        self.e_range_max_line_edit.setObjectName("e_range_max_line_edit")
        self.gridLayout_3.addWidget(self.e_range_max_line_edit, 1, 2, 1, 1)
        self.e_range_min_line_edit = QtWidgets.QLineEdit(
            parent=self.fit_settings_widget
        )
        self.e_range_min_line_edit.setObjectName("e_range_min_line_edit")
        self.gridLayout_3.addWidget(self.e_range_min_line_edit, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.fit_settings_widget, 5, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(parent=self.side_panel_tabs)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMouseTracking(False)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.loaded_fit_table_label = QtWidgets.QLabel(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.loaded_fit_table_label.sizePolicy().hasHeightForWidth()
        )
        self.loaded_fit_table_label.setSizePolicy(sizePolicy)
        self.loaded_fit_table_label.setObjectName("loaded_fit_table_label")
        self.horizontalLayout_4.addWidget(self.loaded_fit_table_label)
        self.fit_table_select_button = QtWidgets.QPushButton(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.fit_table_select_button.sizePolicy().hasHeightForWidth()
        )
        self.fit_table_select_button.setSizePolicy(sizePolicy)
        self.fit_table_select_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.fit_table_select_button.setObjectName("fit_table_select_button")
        self.horizontalLayout_4.addWidget(self.fit_table_select_button)
        self.gridLayout_2.addWidget(self.widget_2, 1, 0, 1, 1)
        self.plot_fit_buttons = QtWidgets.QWidget(parent=self.side_panel_tabs)
        self.plot_fit_buttons.setObjectName("plot_fit_buttons")
        self.gridLayout = QtWidgets.QGridLayout(self.plot_fit_buttons)
        self.gridLayout.setObjectName("gridLayout")
        self.plot_data_button = QtWidgets.QPushButton(parent=self.plot_fit_buttons)
        self.plot_data_button.setObjectName("plot_data_button")
        self.gridLayout.addWidget(self.plot_data_button, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.plot_fit_buttons, 6, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.save_output_button = QtWidgets.QPushButton(parent=self.side_panel_tabs)
        self.save_output_button.setObjectName("save_output_button")
        self.horizontalLayout_5.addWidget(self.save_output_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 9, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.side_panel_tabs)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=self.side_panel_tabs)
        self.widget.setObjectName("widget")
        self.gridLayout_2.addWidget(self.widget, 12, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.gridLayout_2.addItem(spacerItem, 10, 0, 1, 1)
        self.fit_table_data_table = QtWidgets.QTableWidget(parent=self.side_panel_tabs)
        self.fit_table_data_table.setObjectName("fit_table_data_table")
        self.fit_table_data_table.setColumnCount(4)
        self.fit_table_data_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.fit_table_data_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fit_table_data_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fit_table_data_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.fit_table_data_table.setHorizontalHeaderItem(3, item)
        self.gridLayout_2.addWidget(self.fit_table_data_table, 8, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.side_panel_tabs)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 7, 0, 1, 1)
        self.horizontalLayout.addWidget(self.side_panel_tabs)

        self.retranslateUi(fit_table_plot)
        QtCore.QMetaObject.connectSlotsByName(fit_table_plot)

    def retranslateUi(self, fit_table_plot):
        _translate = QtCore.QCoreApplication.translate
        fit_table_plot.setWindowTitle(_translate("fit_table_plot", "Form"))
        self.peak_params_label.setText(_translate("fit_table_plot", "Plot Settings"))
        self.loaded_fit_table_label_2.setText(
            _translate("fit_table_plot", "Plot Parameter")
        )
        self.auto_e_range_label.setText(
            _translate("fit_table_plot", "Momentum Range (MeV)")
        )
        self.plot_parameter_comboBox.setItemText(
            0, _translate("fit_table_plot", "Amplitude")
        )
        self.plot_parameter_comboBox.setItemText(
            1, _translate("fit_table_plot", "Center")
        )
        self.plot_parameter_comboBox.setItemText(
            2, _translate("fit_table_plot", "Sigma")
        )
        self.auto_e_range_label_2.setText(
            _translate("fit_table_plot", "Energy range (KeV)")
        )
        self.loaded_fit_table_label.setText(_translate("fit_table_plot", "TextLabel"))
        self.fit_table_select_button.setText(_translate("fit_table_plot", "Browse"))
        self.plot_data_button.setText(_translate("fit_table_plot", "Plot"))
        self.save_output_button.setText(_translate("fit_table_plot", "Save"))
        self.label.setText(_translate("fit_table_plot", "Select Fit Table"))
        item = self.fit_table_data_table.horizontalHeaderItem(0)
        item.setText(_translate("fit_table_plot", "Run Number"))
        item = self.fit_table_data_table.horizontalHeaderItem(1)
        item.setText(_translate("fit_table_plot", "Momentum"))
        item = self.fit_table_data_table.horizontalHeaderItem(2)
        item.setText(_translate("fit_table_plot", "Plot Parameter"))
        item = self.fit_table_data_table.horizontalHeaderItem(3)
        item.setText(_translate("fit_table_plot", "Uncertainty"))
        self.label_2.setText(_translate("fit_table_plot", "Output"))


from EVA.gui.widgets.plot.plot_widget import PlotWidget


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    fit_table_plot = QtWidgets.QWidget()
    ui = Ui_fit_table_plot()
    ui.setupUi(fit_table_plot)
    fit_table_plot.show()
    sys.exit(app.exec())
