# Form implementation generated from reading ui file 'C:\Users\matea\PycharmProjects\EVA\src\EVA\gui\ui_files\settings_widget.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_settings(object):
    def setupUi(self, settings):
        settings.setObjectName("settings")
        settings.resize(396, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=settings)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.working_dir_browse_button = QtWidgets.QPushButton(parent=self.groupBox)
        self.working_dir_browse_button.setObjectName("working_dir_browse_button")
        self.gridLayout.addWidget(self.working_dir_browse_button, 1, 2, 1, 1)
        self.srim_output_directory_button = QtWidgets.QPushButton(parent=self.groupBox)
        self.srim_output_directory_button.setObjectName("srim_output_directory_button")
        self.gridLayout.addWidget(self.srim_output_directory_button, 5, 2, 1, 1)
        self.srim_exe_dir_button = QtWidgets.QPushButton(parent=self.groupBox)
        self.srim_exe_dir_button.setObjectName("srim_exe_dir_button")
        self.gridLayout.addWidget(self.srim_exe_dir_button, 3, 2, 1, 1)
        self.srim_exe_dir_label = QtWidgets.QLabel(parent=self.groupBox)
        self.srim_exe_dir_label.setObjectName("srim_exe_dir_label")
        self.gridLayout.addWidget(self.srim_exe_dir_label, 3, 0, 1, 2)
        self.working_dir_label = QtWidgets.QLabel(parent=self.groupBox)
        self.working_dir_label.setObjectName("working_dir_label")
        self.gridLayout.addWidget(self.working_dir_label, 1, 0, 1, 2)
        self.srim_out_dir_label = QtWidgets.QLabel(parent=self.groupBox)
        self.srim_out_dir_label.setObjectName("srim_out_dir_label")
        self.gridLayout.addWidget(self.srim_out_dir_label, 5, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=settings)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.plot_fill_colour_button = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.plot_fill_colour_button.setObjectName("plot_fill_colour_button")
        self.gridLayout_2.addWidget(self.plot_fill_colour_button, 0, 2, 1, 1)
        self.plot_fill_colour_preview = QtWidgets.QWidget(parent=self.groupBox_2)
        self.plot_fill_colour_preview.setObjectName("plot_fill_colour_preview")
        self.gridLayout_2.addWidget(self.plot_fill_colour_preview, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=settings)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(settings)
        self.buttonBox.accepted.connect(settings.accept) # type: ignore
        self.buttonBox.rejected.connect(settings.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(settings)

    def retranslateUi(self, settings):
        _translate = QtCore.QCoreApplication.translate
        settings.setWindowTitle(_translate("settings", "Dialog"))
        self.groupBox.setTitle(_translate("settings", "General"))
        self.label_2.setText(_translate("settings", "SRIM directory:"))
        self.label_3.setText(_translate("settings", "SRIM output directory:"))
        self.label.setText(_translate("settings", "Working directory:"))
        self.working_dir_browse_button.setText(_translate("settings", "Browse"))
        self.srim_output_directory_button.setText(_translate("settings", "Browse"))
        self.srim_exe_dir_button.setText(_translate("settings", "Browse"))
        self.srim_exe_dir_label.setText(_translate("settings", "./"))
        self.working_dir_label.setText(_translate("settings", "./"))
        self.srim_out_dir_label.setText(_translate("settings", "./"))
        self.groupBox_2.setTitle(_translate("settings", "Plotting"))
        self.label_7.setText(_translate("settings", "Default plot fill colour"))
        self.plot_fill_colour_button.setText(_translate("settings", "Edit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    settings = QtWidgets.QDialog()
    ui = Ui_settings()
    ui.setupUi(settings)
    settings.show()
    sys.exit(app.exec())
