# Form implementation generated from reading ui file 'C:\Users\matea\PycharmProjects\EVA\src\EVA\gui\ui_files\test_main_window.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        MainWindow.resize(969, 669)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter.setMinimumSize(QtCore.QSize(10, 0))
        self.splitter.setStyleSheet("")
        self.splitter.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(5)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(parent=self.splitter)
        self.frame.setMinimumSize(QtCore.QSize(200, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setContentsMargins(9, 0, 3, 9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    border-radius: 6px;\n"
"    margin-top: 6px;\n"
"    background-color: white;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 7px;\n"
"    padding: 2px 5px 2px 5px;\n"
"    background-color: white;\n"
"    border: 1px solid #E8E8E8;\n"
"    border-radius: 2px\n"
"}")
        self.groupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setContentsMargins(-1, 12, -1, 8)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comment_text = QtWidgets.QTextBrowser(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comment_text.sizePolicy().hasHeightForWidth())
        self.comment_text.setSizePolicy(sizePolicy)
        self.comment_text.setObjectName("comment_text")
        self.verticalLayout_4.addWidget(self.comment_text)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    border-radius: 6px;\n"
"    margin-top: 6px;\n"
"    background-color: white;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 7px;\n"
"    padding: 2px 5px 2px 5px;\n"
"    background-color: white;\n"
"    border: 1px solid #E8E8E8;\n"
"    border-radius: 2px\n"
"}")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setContentsMargins(9, 20, 9, 9)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 2)
        self.apply_run_settings_button = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.apply_run_settings_button.setObjectName("apply_run_settings_button")
        self.gridLayout_3.addWidget(self.apply_run_settings_button, 10, 0, 1, 2)
        self.normalisation_type_combo_box = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.normalisation_type_combo_box.setObjectName("normalisation_type_combo_box")
        self.normalisation_type_combo_box.addItem("")
        self.normalisation_type_combo_box.addItem("")
        self.normalisation_type_combo_box.addItem("")
        self.gridLayout_3.addWidget(self.normalisation_type_combo_box, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 9, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 5, 0, 1, 1)
        self.binning_spin_box = QtWidgets.QDoubleSpinBox(parent=self.groupBox_2)
        self.binning_spin_box.setSuffix("")
        self.binning_spin_box.setMinimum(0.1)
        self.binning_spin_box.setSingleStep(1.0)
        self.binning_spin_box.setProperty("value", 1.0)
        self.binning_spin_box.setObjectName("binning_spin_box")
        self.gridLayout_3.addWidget(self.binning_spin_box, 6, 0, 1, 2)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.logbook_group_box = QtWidgets.QGroupBox(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.logbook_group_box.sizePolicy().hasHeightForWidth())
        self.logbook_group_box.setSizePolicy(sizePolicy)
        self.logbook_group_box.setStyleSheet("QGroupBox {\n"
"    border-radius: 6px;\n"
"    margin-top: 6px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 7px;\n"
"    padding: 2px 5px 2px 5px;\n"
"    background-color: white;\n"
"    border: 1px solid #E8E8E8;\n"
"    border-radius: 2px\n"
"}")
        self.logbook_group_box.setFlat(False)
        self.logbook_group_box.setObjectName("logbook_group_box")
        self.gridLayout = QtWidgets.QGridLayout(self.logbook_group_box)
        self.gridLayout.setContentsMargins(9, 12, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.logbook_group_box)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 2, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(parent=self.logbook_group_box)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 2)
        self.comboBox = QtWidgets.QComboBox(parent=self.logbook_group_box)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(parent=self.logbook_group_box)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.verticalLayout_5.addWidget(self.logbook_group_box)
        self.frame_2 = QtWidgets.QFrame(parent=self.splitter)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setContentsMargins(3, 0, -1, 9)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.frame_2)
        self.tabWidget.setElideMode(QtCore.Qt.TextElideMode.ElideRight)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout_8.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 969, 22))
        self.menubar.setStyleSheet("border-bottom: 1px solid lightgrey;\n"
"margin: 0px;\n"
"padding: 0;")
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(parent=self.menubar)
        self.file_menu.setObjectName("file_menu")
        self.plot_menu = QtWidgets.QMenu(parent=self.menubar)
        self.plot_menu.setObjectName("plot_menu")
        self.settings_menu = QtWidgets.QMenu(parent=self.menubar)
        self.settings_menu.setObjectName("settings_menu")
        self.analysis_menu = QtWidgets.QMenu(parent=self.menubar)
        self.analysis_menu.setObjectName("analysis_menu")
        self.peak_fit_menu = QtWidgets.QMenu(parent=self.analysis_menu)
        self.peak_fit_menu.setObjectName("peak_fit_menu")
        self.tools_menu = QtWidgets.QMenu(parent=self.menubar)
        self.tools_menu.setObjectName("tools_menu")
        self.help_menu = QtWidgets.QMenu(parent=self.menubar)
        self.help_menu.setObjectName("help_menu")
        MainWindow.setMenuBar(self.menubar)
        self.trim_simulation = QtGui.QAction(parent=MainWindow)
        self.trim_simulation.setObjectName("trim_simulation")
        self.model_muon_spectrum = QtGui.QAction(parent=MainWindow)
        self.model_muon_spectrum.setObjectName("model_muon_spectrum")
        self.periodic_table = QtGui.QAction(parent=MainWindow)
        self.periodic_table.setObjectName("periodic_table")
        self.help_manual = QtGui.QAction(parent=MainWindow)
        self.help_manual.setObjectName("help_manual")
        self.energy_corrections = QtGui.QAction(parent=MainWindow)
        self.energy_corrections.setObjectName("energy_corrections")
        self.plot_multiplot = QtGui.QAction(parent=MainWindow)
        self.plot_multiplot.setObjectName("plot_multiplot")
        self.actiontest = QtGui.QAction(parent=MainWindow)
        self.actiontest.setObjectName("actiontest")
        self.file_load_default = QtGui.QAction(parent=MainWindow)
        self.file_load_default.setObjectName("file_load_default")
        self.file_browse_dir = QtGui.QAction(parent=MainWindow)
        self.file_browse_dir.setObjectName("file_browse_dir")
        self.file_reset = QtGui.QAction(parent=MainWindow)
        self.file_reset.setObjectName("file_reset")
        self.change_settings = QtGui.QAction(parent=MainWindow)
        self.change_settings.setObjectName("change_settings")
        self.file_menu.addAction(self.file_reset)
        self.plot_menu.addAction(self.plot_multiplot)
        self.settings_menu.addAction(self.change_settings)
        self.peak_fit_menu.addAction(self.actiontest)
        self.analysis_menu.addAction(self.peak_fit_menu.menuAction())
        self.tools_menu.addAction(self.trim_simulation)
        self.tools_menu.addAction(self.model_muon_spectrum)
        self.tools_menu.addAction(self.periodic_table)
        self.help_menu.addAction(self.help_manual)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.plot_menu.menuAction())
        self.menubar.addAction(self.settings_menu.menuAction())
        self.menubar.addAction(self.analysis_menu.menuAction())
        self.menubar.addAction(self.tools_menu.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Run Info"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Run Settings"))
        self.label_2.setText(_translate("MainWindow", "Normalisation type"))
        self.apply_run_settings_button.setText(_translate("MainWindow", "Apply"))
        self.normalisation_type_combo_box.setItemText(0, _translate("MainWindow", "None"))
        self.normalisation_type_combo_box.setItemText(1, _translate("MainWindow", "Normalisation by counts"))
        self.normalisation_type_combo_box.setItemText(2, _translate("MainWindow", "Normalisation by events"))
        self.label_3.setText(_translate("MainWindow", "Binning"))
        self.logbook_group_box.setTitle(_translate("MainWindow", "Logbook history"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">[10/4/25 14:48] Added 2 figures to logbook.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Create new logbook"))
        self.label.setText(_translate("MainWindow", "Select logbook"))
        self.file_menu.setTitle(_translate("MainWindow", "File"))
        self.plot_menu.setTitle(_translate("MainWindow", "Plot"))
        self.settings_menu.setTitle(_translate("MainWindow", "Settings"))
        self.analysis_menu.setTitle(_translate("MainWindow", "Analysis"))
        self.peak_fit_menu.setTitle(_translate("MainWindow", "Peak Fitting"))
        self.tools_menu.setTitle(_translate("MainWindow", "Tools"))
        self.help_menu.setTitle(_translate("MainWindow", "Help"))
        self.trim_simulation.setText(_translate("MainWindow", "SRIM/TRIM simulation"))
        self.model_muon_spectrum.setText(_translate("MainWindow", "Simulate Muonic X-ray Spectra"))
        self.periodic_table.setText(_translate("MainWindow", "Periodic Table"))
        self.help_manual.setText(_translate("MainWindow", "Manual"))
        self.energy_corrections.setText(_translate("MainWindow", "Energy corrections"))
        self.plot_multiplot.setText(_translate("MainWindow", "Multi-run Plot"))
        self.actiontest.setText(_translate("MainWindow", "test"))
        self.file_load_default.setText(_translate("MainWindow", "Load default settings"))
        self.file_browse_dir.setText(_translate("MainWindow", "Browse to data directory"))
        self.file_reset.setText(_translate("MainWindow", "Reset all settings"))
        self.change_settings.setText(_translate("MainWindow", "Update settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
