# Form implementation generated from reading ui file 'C:\Users\matea\PycharmProjects\EVA\src\EVA\gui\trim_fit.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_trim_fit(object):
    def setupUi(self, trim_fit):
        trim_fit.setObjectName("trim_fit")
        trim_fit.resize(832, 669)
        self.horizontalLayout = QtWidgets.QHBoxLayout(trim_fit)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_panel = QtWidgets.QWidget(parent=trim_fit)
        self.side_panel.setMinimumSize(QtCore.QSize(500, 0))
        self.side_panel.setMaximumSize(QtCore.QSize(600, 16777215))
        self.side_panel.setObjectName("side_panel")
        self.gridLayout = QtWidgets.QGridLayout(self.side_panel)
        self.gridLayout.setObjectName("gridLayout")
        self.result_text_edit = QtWidgets.QTextEdit(parent=self.side_panel)
        self.result_text_edit.setObjectName("result_text_edit")
        self.gridLayout.addWidget(self.result_text_edit, 2, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=self.side_panel)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setObjectName("formLayout")
        self.momentum_label = QtWidgets.QLabel(parent=self.widget)
        self.momentum_label.setObjectName("momentum_label")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.momentum_label
        )
        self.momentum_line_edit = QtWidgets.QLineEdit(parent=self.widget)
        self.momentum_line_edit.setObjectName("momentum_line_edit")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.momentum_line_edit
        )
        self.fit_button = QtWidgets.QPushButton(parent=self.widget)
        self.fit_button.setObjectName("fit_button")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.fit_button
        )
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setObjectName("widget_2")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.widget_2
        )
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.layer_table = BaseTable(parent=self.side_panel)
        self.layer_table.setObjectName("layer_table")
        self.layer_table.setColumnCount(3)
        self.layer_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.layer_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.layer_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.layer_table.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.layer_table, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.side_panel)
        self.widget_3 = QtWidgets.QWidget(parent=trim_fit)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plot = PlotWidget(parent=self.widget_3)
        self.plot.setObjectName("plot")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.plot)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addWidget(self.plot)
        self.trim_plot = PlotWidget(parent=self.widget_3)
        self.trim_plot.setObjectName("trim_plot")
        self.verticalLayout_2.addWidget(self.trim_plot)
        self.horizontalLayout.addWidget(self.widget_3)

        self.retranslateUi(trim_fit)
        QtCore.QMetaObject.connectSlotsByName(trim_fit)

    def retranslateUi(self, trim_fit):
        _translate = QtCore.QCoreApplication.translate
        trim_fit.setWindowTitle(_translate("trim_fit", "Form"))
        self.momentum_label.setText(_translate("trim_fit", "Momentum"))
        self.fit_button.setText(_translate("trim_fit", "go!!!!"))
        item = self.layer_table.horizontalHeaderItem(0)
        item.setText(_translate("trim_fit", "Sample"))
        item = self.layer_table.horizontalHeaderItem(1)
        item.setText(_translate("trim_fit", "Thickness"))
        item = self.layer_table.horizontalHeaderItem(2)
        item.setText(_translate("trim_fit", "Density"))


from EVA.gui.base.base_table import BaseTable
from EVA.gui.widgets.plot.plot_widget import PlotWidget


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    trim_fit = QtWidgets.QWidget()
    ui = Ui_trim_fit()
    ui.setupUi(trim_fit)
    trim_fit.show()
    sys.exit(app.exec())
