name: Create executable

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
      - uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'EVA.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'EVA'
          options: --onefile, --name "EVA", --windowed
